- name: Download ODL yum repo
  get_url:
    url={{ rpm_repo_url }}
    dest=/etc/yum.repos.d/{{ rpm_repo_file }}
- name: Set ODL yum repo file properties
  file:
    path=/etc/yum.repos.d/{{ rpm_repo_file }}
    owner=root
    group=root
    mode=0644
