- name: Download ODL yum repo
  get_url:
    url={{ rpm_repo_url }}
    dest=/etc/yum.repos.d/opendaylight.repo
- name: Set ODL yum repo file properties
  file:
    path=/etc/yum.repos.d/opendaylight.repo
    owner=root
    group=root
    mode=0644
