---
- hosts: all
  become: yes
  roles:
    - role: opendaylight
      # Install latest service release of ODL Boron RPM from the CBS repos
      rpm_repo_file: "opendaylight-5-release.repo"
      rpm_repo_url: "https://git.opendaylight.org/gerrit/gitweb?p=integration/packaging.git;a=blob_plain;f=rpm/example_repo_configs/opendaylight-5-release.repo"
