# common variables
---
# network infrastructure
## lab network resources
# lab_http_proxy:
# lab_https_proxy:
# infrastructure_server:
# registry_ip_address:
# docker_registry_port:
# docker_registry:


## network configuration of host machines
mgmt_iface: eno3
data_iface: eno4
management_bridge: br_mgmt
data_bridge: br_data
test_netmask: 16
management_interface: "{{ mgmt_iface }}"
data_interface: "{{ data_iface }}"
management_subnet_prefix: "10.129"
mgmt_ip_prefix: "10.129"
management_subnet_netmask: "16"
data_subnet_prefix: "10.130"
data_ip_prefix: "10.130"
data_subnet_netmask: "16"

# IP address of the Linux bridge on the physical host
mgmt_ip: "{{ mgmt_ip_prefix }}.{{ rackpos }}.1/{{ test_netmask }}"
data_ip: "{{ data_ip_prefix }}.{{ rackpos }}.1/{{ test_netmask }}"

# lab/default IP addresses of physical hosts
mgmt_lab_ip_prefix: "10.11.26"
data_lab_ip_prefix: "10.11.126"
lab_netmask: 22
# position and rackpos are an integer "index" of physical machines
position: "{{ rackpos }}"
# default IP addresses for lab machine interfaces
mgmt_lab_ip: "{{ mgmt_lab_ip_prefix }}.{{ rackpos }}/{{ lab_netmask }}"
data_lab_ip: "{{ data_lab_ip_prefix }}.{{ rackpos }}/{{ lab_netmask }}"

# node operating system defaults
# Variables for emulated framework containers
## container configuration
docker_systemd_version: "v0.1"
compute_image: "s3p/compute"
compute_version: "v0.5s"
measure_image: "s3p/measure"
measure_version: "v0.1.1"
service_image: "s3p/service"
service_version: "v0.4sc"
control_node_image: "{{ docker_registry }}/{{ service_image }}:{{ service_version }}"

## cluster configuration
### the service_host ip should be conform to infrastructure routing
#### service_host_phys_host is the host_index for the physical server
service_host_phys_host: "20"
service_host_container_index: "2"
service_host_mgmt_ip: "{{ management_subnet_prefix }}.{{ service_host_phys_host }}.{{ service_host_container_index }}"
control_node_container_name: "service-node"

# network parameters for service and compute nodes
lab_no_proxy: "localhost,10.0.0.0/8,192.168.0.0/16,172.17.0.0/16,127.0.0.1,127.0.0.0/8,{{ service_host_mgmt_ip }}"

# OpenStack framework config
use_odl_network: "True"
